--
-- Name: tb_associado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_associado (
    id integer NOT NULL,
    cpf character varying(255),
    nome character varying(255)
);


--
-- Name: tb_associado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_associado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_associado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_pauta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_pauta (
    id_pauta integer NOT NULL,
    descricao character varying(255)
);


--
-- Name: tb_pauta_id_pauta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_pauta ALTER COLUMN id_pauta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_pauta_id_pauta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_votacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_votacao (
    decisao character varying(255),
    nao integer NOT NULL,
    sim integer NOT NULL,
    total integer NOT NULL,
    pauta_id_pauta integer NOT NULL
);


--
-- Name: tb_voto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_voto (
    id_voto integer NOT NULL,
    escolha character(1) NOT NULL,
    associado_id integer,
    pauta_id integer
);


--
-- Name: tb_voto_id_voto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_voto ALTER COLUMN id_voto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_voto_id_voto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_associado tb_associado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_associado
    ADD CONSTRAINT tb_associado_pkey PRIMARY KEY (id);


--
-- Name: tb_pauta tb_pauta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_pauta
    ADD CONSTRAINT tb_pauta_pkey PRIMARY KEY (id_pauta);


--
-- Name: tb_votacao tb_votacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_votacao
    ADD CONSTRAINT tb_votacao_pkey PRIMARY KEY (pauta_id_pauta);


--
-- Name: tb_voto tb_voto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_voto
    ADD CONSTRAINT tb_voto_pkey PRIMARY KEY (id_voto);


--
-- Name: tb_votacao fk87rn0lujjdiv8nmcylpv87buc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_votacao
    ADD CONSTRAINT fk87rn0lujjdiv8nmcylpv87buc FOREIGN KEY (pauta_id_pauta) REFERENCES public.tb_pauta(id_pauta);


--
-- Name: tb_voto fkanmwqa0vm44yh63c86aggl3tq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_voto
    ADD CONSTRAINT fkanmwqa0vm44yh63c86aggl3tq FOREIGN KEY (pauta_id) REFERENCES public.tb_pauta(id_pauta);


--
-- Name: tb_voto fkr3qgif8est3ghlp7yjlw618a2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_voto
    ADD CONSTRAINT fkr3qgif8est3ghlp7yjlw618a2 FOREIGN KEY (associado_id) REFERENCES public.tb_associado(id);


--
-- PostgreSQL database dump complete
--

