server:
  port: 8080

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.votacaoAssembleia
      routing-key:
        producer: rk.producer.votacaoAssembleia
      dead-letter:
        producer: dl.producer.votacaoAssembleia
      parking-lot:
        producer: pl.producer.votacaoAssembleia